### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by rizhenkov** [lovata/oc-bootstrap-shopaholic-theme#23]
After installing from "market" we have a error:

`The Mix manifest does not exist.`

![image](https://user-images.githubusercontent.com/987517/48483238-f6fbda00-e823-11e8-845c-302efe238f04.png)

**Comment by rizhenkov** [comment]
To fix that error we need to fix pathes at layouts and partials
(sorry no time to quick PR)
![image](https://user-images.githubusercontent.com/987517/48484096-46dba080-e826-11e8-8946-f83dcf56d06d.png)

**Comment by kharanenka** [comment]
Thanks!

**Comment by kharanenka** [comment]
Fixed in version 1.0.1
