### ISSUE TITLE
[Ask] Issue with compiling resources

### ISSUE THREAD

**Issue by rizhenkov** [lovata/oc-bootstrap-shopaholic-theme#26]
I'll try to change one js file and recompile resources. 
And got some errors when `npm i`
![image](https://user-images.githubusercontent.com/987517/48549861-093c4d80-e8e2-11e8-979a-b20b856cbea4.png)

Not all people uses the compilers like that. Specially if we have built-in one in October CMS ($this->addJs([..])).
If it's a "bootstrap" theme I want to quick start developing from that template. Otherwise I need to solve that troubles with minifying :)

Maybe.. Maybe (!) we need to keep all js/css resources clean and simple to help wider circle developers start with it. Or just use built-in compressor without needing side console utilites.

**Comment by kombimedia** [comment]
Hi there,

I am also having issues compiling resources.

When I:

-  run npm install I have a warning;

`npm WARN stylelint-webpack-plugin@0.10.5 requires a peer of stylelint@^8.0.0 but none is installed. You must install peer dependencies yourself.`

If I:

- install version ^8.0.0 I am hit with;

`npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN stylelint-order@1.0.0 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.`

Maybe these are just warnings and not the issue with webpack not running.

If I:

- run npm run dev I get this error message;

`> @ dev /Users/responsive/Documents/Development/octoberstore/themes/lovata-bootstrap-shopaholic
> npm run development


> @ development /Users/responsive/Documents/Development/octoberstore/themes/lovata-bootstrap-shopaholic
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

Error: ENOENT: no such file or directory, open '/Users/responsive/Documents/Development/octoberstore/themes/lovata-bootstrap-shopaholic/.stylelintrc'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/responsive/.npm/_logs/2019-06-21T04_53_13_228Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/responsive/.npm/_logs/2019-06-21T04_53_13_249Z-debug.log
`

This is suggesting the config file is missing? - stylelintrc

Both my webpack.mix.js and package.json files are the theme defaults.

Any ideas?

Thank you,

Cy

**Comment by kombimedia** [comment]
Hi guys. Is there anyone actively supporting this theme?

Cheers,

**Comment by kharanenka** [comment]
Hi! I will check build files and update it on this week.

**Comment by kombimedia** [comment]
Great thanks @kharanenka

**Comment by kharanenka** [comment]
Hi @kombimedia!

Problem turned out to be more complicated than I thought at first. I could not solve it quickly. Assets files is building with error, but files compiles in assets folder. It is necessary to update version of packages that theme uses.

I delegated issue to frontend department. We do not currently have free resources to solve this problem on our own. We try to solve this problem as soon as possible.

**Comment by kombimedia** [comment]
Ok, thanks @kharanenka

**Comment by johnnywo** [comment]
Hi @kharanenka,

... I noticed the same issues like @kombimedia ...
this means, if someone like to modify the theme appearance and recompile it with eg. npm run watch - it is not possible at the moment?
Thank you

**Comment by lautsevich** [comment]
@rizhenkov, @johnnywo, @kombimedia, a new version will be released today. It will fix this issue.

**Comment by johnnywo** [comment]
Really great news! Thanks a lot @lautsevich!

**Comment by kombimedia** [comment]
That's awesome @lautsevich ! Thanks you so much.

**Comment by lautsevich** [comment]
By the way, we released 1.3.0 version this week. There are a lot of improvements for better Lighthouse report results!

![image](https://user-images.githubusercontent.com/196445/67951946-88af5380-fbfd-11e9-9097-75189e672dff.png)

![image](https://user-images.githubusercontent.com/196445/67951963-91a02500-fbfd-11e9-9414-35c50de445a3.png)

![image](https://user-images.githubusercontent.com/196445/67951989-99f86000-fbfd-11e9-933b-a52b5d8bdd3f.png)
