### ISSUE TITLE
Product page gives 404

### ISSUE THREAD

**Issue by briddle** [lovata/oc-bootstrap-shopaholic-theme#32]
When I:
- use Shopaholic plugin with only the toolbox plugin and the orders plugin
- create a single category (women)
- create a single product (demo) for this category

The shopaholic theme creates links to the product page: _women/default/demo_

This results in a 404 for me...

P.S. The URL field for the page "Product page" is different from that in the docs. In the theme it is: _/:main_category/:category/:slug_

This results in a 404 for me...

**Comment by kharanenka** [comment]
Bootstrap theme provides an example of 2-level catalog. You can change URL for your project. If your catalog has one level, then you can change URL of product page and remove component from product page.
For example:
```twig
title = "Product page"
url = "/:category/:slug"
layout = "main"
is_hidden = 0

[CategoryPage]
slug = "{{ :category }}"
slug_required = 1
smart_url_check = 0

[ProductPage]
slug = "{{ :slug }}"
slug_required = 1
smart_url_check = 1
==
{% set obProduct = ProductPage.get() %}
{% set obCategory = CategoryPage.get() %}
```
