### ISSUE TITLE
Need Demo Data for the Theme

### ISSUE THREAD

**Issue by mnrafg** [lovata/oc-bootstrap-shopaholic-theme#47]
Hello!

I'm a paid Shopaholic user and purchased different paid extensions of Shopaholic developed by Andrey, I really appreciate the plugins, as I'm new to OctoberCMS and have an e-commerce project where I want to integrate the Shopaholic plugin and its extensions with a custom theme that I want to develop for a shop so I'm using this demo theme to cheat from and it really boosted my productivity but there is just a little hardness, I want to have a demo data for these plugins so I can import all the catalog categories, products, offers, and its images at once and can test it better and quicker.

However, the docs for the whole Shopaholic ecosystem at [shopaholic.one](https://shopaholic.one/docs) are not bad but still, I have some questions so where to ask them and how to get quick answers.

Thanks,
Nasir Rahimi

**Comment by lautsevich** [comment]
Hi @mnrafg, sorry for the delay! You can use [Fake Data for Shopaholic plugin](https://octobercms.com/plugin/lovata-fakedatashopaholic) to seed your catalog with goods.

As for the support feel free to contact us these ways:
- https://lovata.com/request-form.html
- https://octobercms.com/author/Lovata
- https://twitter.com/oc_shopaholic
- https://www.facebook.com/oc.shopaholic
- https://discord.gg/Nhv7qP3
