### ISSUE TITLE
mix manifest missing

### ISSUE THREAD

**Issue by bmason** [lovata/oc-bootstrap-shopaholic-theme#48]
I am using 1.41 and October updated as of 6/19/21.

npm run prod seems fine

![Capturea](https://user-images.githubusercontent.com/147215/122656221-55d90c80-d10d-11eb-860c-3f451bcaf0be.PNG)

when I enable the  theme

![Capture](https://user-images.githubusercontent.com/147215/122656277-ca13b000-d10d-11eb-980b-2916c3412cfd.PNG)

I am operating under XAMPP on Windows 10.

**Comment by igor-tv** [comment]
Try reinstalling npm dependencies. Also try running other commands first, like `npm run dev`. Make sure you have [this line](https://github.com/oc-shopaholic/oc-bootstrap-shopaholic-theme/blob/9a5e703df376d0163415da87c6274dbb4e3a334f/webpack.mix.js#L33) in your webpack.mix.js

**Comment by rashedshaon** [comment]
Can not run the theme. Show the following error.

    The Mix manifest does not exist.
Install NPM and done all necessary steps.
![enter image description here](https://i.ibb.co/j4v7VbD/Screenshot-9.jpg)

**Comment by rashedshaon** [comment]
> Try reinstalling npm dependencies. Also try running other commands first, like `npm run dev`. Make sure you have [this line](https://github.com/oc-shopaholic/oc-bootstrap-shopaholic-theme/blob/9a5e703df376d0163415da87c6274dbb4e3a334f/webpack.mix.js#L33) in your webpack.mix.js

Not working like you.

**Comment by kharanenka** [comment]
Hi! I see that you have changed default theme folder. Try to change "code" value in thene.yaml file

**Comment by bmason** [comment]
I misunderstood the child mechanism in October.  I duplicated the theme and removed the .themelock file.  My guess is that file caused the system to look in '-child'.
